# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_hotreload` gem.
# Please instead update this file by running `bin/tapioca gem rails_hotreload`.

# source://rails_hotreload//lib/rails_hotreload/version.rb#3
module RailsHotreload; end

# source://rails_hotreload//lib/rails_hotreload.rb#10
class RailsHotreload::Checker
  # @return [Checker] a new instance of Checker
  #
  # source://rails_hotreload//lib/rails_hotreload.rb#13
  def initialize(paths); end

  # source://rails_hotreload//lib/rails_hotreload.rb#17
  def call; end

  # Returns the value of attribute paths.
  #
  # source://rails_hotreload//lib/rails_hotreload.rb#11
  def paths; end

  private

  # TODO: detach delays when consecutive changes
  #
  # source://rails_hotreload//lib/rails_hotreload.rb#27
  def stream_reload; end
end

# source://rails_hotreload//lib/rails_hotreload/railtie.rb#5
class RailsHotreload::Railtie < ::Rails::Railtie; end

# source://rails_hotreload//lib/rails_hotreload/version.rb#4
RailsHotreload::VERSION = T.let(T.unsafe(nil), String)
